### ISSUE TITLE
Maven dependency for osmbonuspack

### ISSUE THREAD

**Issue by GoogleCodeExporter** [MKergall/osmbonuspack#114] opened 2015-03-26 21:19 UTC
```
Clould yo add the osmbonuspack to Maven Central? It is wery convinient to add 
the dependency to the maven projects and it will increase the usage of your 
library drmmatically!


```

Original issue reported on code.google.com by `ilya.evl...@gmail.com` on 21 Mar 2015 at 12:41

**Comment by k3b** [comment] 2015-04-15 09:38
This is a duplicate of #108

**Closed** 2015-07-31 19:38 UTC
Labels: auto-migrated, Priority-Medium, Type-Defect
