### ISSUE TITLE
Failed to resolve

### ISSUE THREAD

**Issue by bclareton** [MKergall/osmbonuspack#423] opened 2022-06-16 13:30 UTC
{English version}
Hello,

I want to use osmbonuspack for the KML support but, when I build my project, I get a 'Failed to resolve: com.github.MKergall:osmbonuspack:6.9.0' Warning and I don't know how to solved this problem.

I add 
`maven { url 'https://jitpack.io' }`
to my build.gradle (project version)
and
`implementation 'com.github.MKergall:osmbonuspack:6.9.0'`
to my build.gradle (app version)

Thanks for the help.

{French version}
Bonjour,

Je veux utiliser osmbonuspack pour le support du KML mais, quand je build mon projet, j'ai un warning 'Failed to resolve: com.github.MKergall:osmbonuspack:6.9.0' et je ne sais pas comment régler ce problème.

j'ai ajouté
`maven { url 'https://jitpack.io' }`
à mon build.gradle (version project)
et
`implementation 'com.github.MKergall:osmbonuspack:6.9.0'`
à mon build.gradle (version app)

Merci pour le coup de main.

**Comment by eclectice** [comment] 2022-09-28 10:41
The problem is a lookup from https://jitpack.io/#com.github.MKergall/osmbonuspack returns nothing

**Comment by eclectice** [comment] 2022-09-28 10:43
A lookup from https://mvnrepository.com/artifact/com.github.MKergall/osmbonuspack returns 6.6.0 as the latest version

**Comment by eclectice** [comment] 2022-09-29 00:40
It is now ok
![image](https://user-images.githubusercontent.com/1452656/192912968-7c3f7e4b-9853-48e7-9c7e-335554a29dd3.png)

**Comment by MKergall** [comment] 2022-09-30 06:57
We can close this one?

**Comment by eclectice** [comment] 2022-09-30 22:58
> We can close this one?

Although I am not the original poster, I agree that it can now be closed.

**Closed** 2022-10-03 05:41 UTC
