### ISSUE TITLE
Markers get drawn at the wrong screenposition (Zoom > 21)

### ISSUE THREAD

**Issue by JSchriewer** [MKergall/osmbonuspack#208] opened 2016-02-16 13:40 UTC
The problem is that markers and polylines are drawn at the wrong position on the Screen if the zoom is higher than 21. The x-coordinate seems fine, but the y-coordinate get values like 1073742404, so that the marker wont show up on the screen.

I think there is a bug in Projection.toPixels(), but im not sure.

**Comment by spyhunter99** [comment] 2016-02-16 14:06
I'm pretty sure this is a known issue. It's overflowing the maximum capacity for integer. there was some work to convert to doubles, but it's not a bonus pack issue, it's an osmdroid issue.

**Comment by JSchriewer** [comment] 2016-02-16 16:10
Should i repost the issue in the Osmdroid Github and is there a known workaround?

**Comment by MKergall** [comment] 2016-02-16 18:03
Effectively, osmdroid issue. Already raised here: 
https://github.com/osmdroid/osmdroid/issues/46
https://github.com/osmdroid/osmdroid/pull/48

No workaround, but this work in progress => https://github.com/osmdroid/osmdroid/tree/doubles

**Comment by spyhunter99** [comment] 2016-02-20 12:36
@MKergall i wonder if converting from ints to longs would be a simpler solution that converting to doubles. The double branch works, it just takes more ram to run (way more than it should actually)

**Comment by MKergall** [comment] 2016-02-20 18:14
long and double both take 64 bits - so, similar memory increase can be expected. 
And using longs will imply to change "1E6" conversion ratio to something higher, everywhere. 
I will try to have a look why double branch takes so much RAM.

**Comment by spyhunter99** [comment] 2016-06-12 14:31
some related work. turns out it's not a simple solution. The root cause is the View.scrollTo which is part of the android ecosystem.

**Comment by kjeremy** [comment] 2016-08-16 18:51
Is this fixed now that doubles has been merged in?

**Comment by spyhunter99** [comment] 2016-08-16 22:28
@kjeremy feel free to test it and report back

**Comment by MKergall** [comment] 2018-07-20 19:45
Certainly solved from osmdroid 6.0 (with double values everywhere).

**Closed by MKergall** 2018-07-20 19:45 UTC
